### ISSUE TITLE
No Issue Just a Compliment

### ISSUE THREAD

**Issue by shad0whawk** [77QingLiu/vscode-SAS.tmLanguage#1]
Thank you for taking the time to create this file.  I'm hoping you keep building it out and improving it.  I've had a huge need for this and your version is by far the best and most complete one I've come across.  Thanks!

**Comment by 77QingLiu** [comment]
Thanks very much for your compliment, I am very grateful that this can help you. and If you have any problems with this syntax highlighter please don't hesitate to raise an issue here. :)

**Comment by shad0whawk** [comment]
I do have a question. I see there's a #macrovar embedded in #macro that looks like it's supposed to highlight macro variables throughout the program beginning with "&", but that doesn't seem to work.  I've tried tweaking it but still can't get it to work.

**Comment by shad0whawk** [comment]
I can attach it when I get home, but it’s a simple test program that only includes a very generic proc sql and a data step. It didn’t work on my original program so I wrote a few lines of code and still can’t get it two work. I also tried it outside of a data step and proc sql and get the same results. The regex expression works fine in a regex tester.

**Comment by shad0whawk** [comment]
Here's the code:

%let testvar = 1 ;
%put &testvar. ;

PROC SQL ;
	CREATE TABLE PROJ.Z AS
	SELECT * FROM PROJ.X
	WHERE &testvar = 1
	GROUP BY 1,2
QUIT ;

DATA PROJ.Z ;
	SET PROJ.X ;
	if field = &testvar. then output ;
	format test $1. ;
	informat test $1. ;
RUN ;

Screen shot link:
[2018-06-20_22-36-07.pdf](https://github.com/77QingLiu/vscode-SAS.tmLanguage/files/2122042/2018-06-20_22-36-07.pdf)

**Comment by 77QingLiu** [comment]
The dark theme your used don't support highlight Macro Var.
Suggest you switch to the SAS theme in this package like below or choose
another theme.

[image: 屏幕快照 2018-06-21 下午1.48.19.png]


shad0whawk <notifications@github.com> 于2018年6月21日周四 下午12:37写道：

**Comment by shad0whawk** [comment]
ah nice catch! That's a bummer but I will use a different theme.  I didn't realize that the theme could impact it.

**Comment by shad0whawk** [comment]
I like how you theme shows everything correctly which is lacking in other themes; however, the white is so bright.  Is there anyway you could create a dark version of your theme?

**Comment by 77QingLiu** [comment]
You can refer the official documents(add themes, syntax
<https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers>)
if you are interested.
The dark theme Dark+(default dark) in vscode is a good choice for
highlighting and there is no need to create another dark theme.
[image: 屏幕快照 2018-06-22 上午8.37.41.png]
And also you definitely could find some dark theme in marketplace suite for
this syntax.

shad0whawk <notifications@github.com> 于2018年6月22日周五 上午1:36写道：

**Comment by shad0whawk** [comment]
Thank you I’ll check it out.

**Comment by 77QingLiu** [comment]
np
